// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCEaF4TMtGmHFtFXslCiaGCBhXPvUUFGQ',
    appId: '1:790348975994:web:4bac48cbef4a6e6e0450c3',
    messagingSenderId: '790348975994',
    projectId: 'bsafinfoapp',
    authDomain: 'bsafinfoapp.firebaseapp.com',
    storageBucket: 'bsafinfoapp.appspot.com',
    measurementId: 'G-KFNCQZ7TKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXUV4Ytg7UBOs0SxpU66OBILbUrK5oZRk',
    appId: '1:790348975994:android:aa52e37e826943870450c3',
    messagingSenderId: '790348975994',
    projectId: 'bsafinfoapp',
    storageBucket: 'bsafinfoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBklA-_6dnfgoyp-VTTMMMoeUaXZD0nEqE',
    appId: '1:790348975994:ios:cc6078fa0600098e0450c3',
    messagingSenderId: '790348975994',
    projectId: 'bsafinfoapp',
    storageBucket: 'bsafinfoapp.appspot.com',
    iosClientId: '790348975994-520qg0rpo11k8p0kla3ksp32tqg0ebjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bsafproductinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBklA-_6dnfgoyp-VTTMMMoeUaXZD0nEqE',
    appId: '1:790348975994:ios:6158451f528d597a0450c3',
    messagingSenderId: '790348975994',
    projectId: 'bsafinfoapp',
    storageBucket: 'bsafinfoapp.appspot.com',
    iosClientId: '790348975994-7a0al2i6021v9cpvr0h1724sd3bggos0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bsafproductinfo.RunnerTests',
  );
}
